name: mysql-port-mapping-test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Wait for MySQL on 127.0.0.1:3306
        run: |
          for i in {1..5}; do
            nc -z 127.0.0.1 3306 && echo "MySQL is up!" && exit 0
            echo "Waiting for MySQL on 127.0.0.1:3306..."
            sleep 2
          done
          echo "MySQL did not become available in time!" && exit 1

      - name: Test MySQL connection
        run: |
          mysql -h127.0.0.1 -uroot -ppassword -e "SHOW DATABASES;"
